# Generated by Django 4.0.2 on 2022-04-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
    ]
